import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    nav_home: "Home", nav_about: "About Us", nav_services: "Services",
    nav_projects: "Projects", nav_whysolar: "Why Solar", nav_testimonials: "Testimonials",
    nav_contact: "Contact Us", nav_cta: "Get a Free Quote →",
    hero_tag: "Powering a Brighter Future", hero_h1a: "Smart Solar", hero_h1b: "Solutions for",
    hero_h1c: "a", hero_h1d: "Better Tomorrow",
    hero_p: "Narhare Solar Solutions provides efficient, reliable and affordable solar energy systems for homes, businesses and industries.",
    hero_btn1: "Get a Free Quote →", hero_btn2: "Explore Services →",
    hero_stat1: "Projects Completed", hero_stat2: "Customer Satisfaction", hero_stat3: "Years of Experience",
    feat1_title: "Save on Electricity Bills", feat1_desc: "Reduce your energy bills up to 80% with solar power.",
    feat2_title: "Clean & Green Energy", feat2_desc: "Eco-friendly energy that helps protect our planet.",
    feat3_title: "Reliable & Durable", feat3_desc: "High quality systems built to last for decades.",
    feat4_title: "Expert Support", feat4_desc: "From consultation to after sales support – always with you.",
    about_tag: "About Us", about_h2: "Building a Sustainable Future with Solar Energy",
    about_p: "Narhare Solar Solutions is a leading provider of solar energy solutions in India. We are committed to delivering high-quality, cost-effective and sustainable solar systems tailored to your needs.",
    about_li1: "Tailored solar solutions for every need", about_li2: "High quality products & advanced technology",
    about_li3: "Professional installation by expert team", about_li4: "Timely delivery & reliable service",
    about_btn: "Know More About Us →",
    svc_tag: "Our Services", svc_h2a: "Complete Solar Solutions", svc_h2b: "for Every Need",
    svc1_title: "Rooftop Solar Solutions", svc1_desc: "Customized rooftop solar systems for homes and businesses.",
    svc2_title: "Commercial Solar Solutions", svc2_desc: "Power your business with high-performance solar systems.",
    svc3_title: "Solar Installation & Commissioning", svc3_desc: "End-to-end installation and commissioning by our expert team.",
    svc4_title: "Operation & Maintenance", svc4_desc: "Keep your system efficient with our reliable O&M services.",
    svc_learn: "Learn More →",
    why_tag: "Why Solar?", why_h2a: "Benefits That", why_h2b: "Make a Difference",
    why1_title: "Reduce Electricity Bills", why1_desc: "Save up to 80% on your monthly electricity bills.",
    why2_title: "Increase Property Value", why2_desc: "Homes and businesses with solar have higher value.",
    why3_title: "Energy Independence", why3_desc: "Generate your own power and be independent from rising electricity prices.",
    why4_title: "Environment Friendly", why4_desc: "Reduce carbon footprint and contribute to a cleaner planet.",
    proc_tag: "Our Process", proc_h2: "Our Simple 4-Step Process",
    proc1_title: "Consultation", proc1_desc: "We understand your needs and analyze your requirements.",
    proc2_title: "Site Survey", proc2_desc: "Our experts visit your site and do a detailed assessment.",
    proc3_title: "Proposal", proc3_desc: "We provide a custom proposal with the best solar solution.",
    proc4_title: "Installation", proc4_desc: "Professional installation and commissioning with full support.",
    testi_tag: "Testimonials", testi_h2: "What Our Clients Say",
    proj_tag: "Our Projects", proj_h2: "Some of Our Recent Projects", proj_view: "View All Projects →",
    cta_h3: "Ready to Switch to Solar Energy?",
    cta_p: "Get a free consultation and customized solution for your energy needs.",
    cta_btn: "Get a Free Quote →",
    contact_tag: "Get in Touch", contact_h2: "Get a Free Quote",
    contact_p: "Fill the form and our team will get back to you shortly.",
    contact_info_title: "Contact Information",
    contact_phone_label: "Phone", contact_email_label: "Email",
    contact_office_label: "Office", contact_hours_label: "Working Hours",
    contact_hours_val: "Mon - Sat: 9:00 AM - 6:00 PM", contact_follow: "Follow Us",
    form_name: "Full Name", form_name_ph: "Enter your name",
    form_phone: "Phone Number", form_phone_ph: "Enter your phone number",
    form_email: "Email Address", form_email_ph: "Enter your email address",
    form_city: "City", form_city_ph: "Enter your city",
    form_service: "What are you looking for?", form_service_ph: "Select an option",
    form_svc1: "Rooftop Solar Solutions", form_svc2: "Commercial Solar Solutions",
    form_svc3: "Solar Installation & Commissioning", form_svc4: "Operation & Maintenance",
    form_message: "Your Message", form_message_ph: "Write your message...",
    form_submit: "Submit Now →", form_sending: "Sending...",
    form_success: "✅ Message sent! We'll contact you soon.",
    form_error: "❌ Something went wrong. Please call us directly.",
    footer_desc: "Powering a sustainable future with smart solar solutions.",
    footer_links: "Quick Links", footer_services: "Our Services", footer_contact: "Contact Us",
    footer_copy: "© 2024 Narhare Solar Solutions. All Rights Reserved.",
    footer_privacy: "Privacy Policy", footer_terms: "Terms & Conditions",
  },
  hi: {
    nav_home: "होम", nav_about: "हमारे बारे में", nav_services: "सेवाएं",
    nav_projects: "प्रोजेक्ट्स", nav_whysolar: "सोलर क्यों?", nav_testimonials: "ग्राहक समीक्षा",
    nav_contact: "संपर्क करें", nav_cta: "मुफ्त कोटेशन लें →",
    hero_tag: "एक उज्जवल भविष्य की ओर", hero_h1a: "स्मार्ट सोलर", hero_h1b: "समाधान",
    hero_h1c: "एक", hero_h1d: "बेहतर कल के लिए",
    hero_p: "नरहरे सोलर सॉल्यूशंस घरों, व्यवसायों और उद्योगों के लिए कुशल, विश्वसनीय और किफायती सौर ऊर्जा प्रणालियां प्रदान करता है।",
    hero_btn1: "मुफ्त कोटेशन लें →", hero_btn2: "सेवाएं देखें →",
    hero_stat1: "पूर्ण प्रोजेक्ट्स", hero_stat2: "ग्राहक संतुष्टि", hero_stat3: "वर्षों का अनुभव",
    feat1_title: "बिजली बिल बचाएं", feat1_desc: "सोलर पावर से अपने बिजली बिल को 80% तक कम करें।",
    feat2_title: "स्वच्छ और हरित ऊर्जा", feat2_desc: "पर्यावरण के अनुकूल ऊर्जा जो हमारे ग्रह की रक्षा करती है।",
    feat3_title: "विश्वसनीय और टिकाऊ", feat3_desc: "दशकों तक चलने के लिए बने उच्च गुणवत्ता वाले सिस्टम।",
    feat4_title: "विशेषज्ञ सहायता", feat4_desc: "परामर्श से लेकर बिक्री के बाद सहायता तक – हम हमेशा आपके साथ।",
    about_tag: "हमारे बारे में", about_h2: "सौर ऊर्जा से एक टिकाऊ भविष्य का निर्माण",
    about_p: "नरहरे सोलर सॉल्यूशंस भारत में सौर ऊर्जा समाधानों का एक अग्रणी प्रदाता है। हम आपकी जरूरतों के अनुसार उच्च गुणवत्ता, किफायती और टिकाऊ सोलर सिस्टम देने के लिए प्रतिबद्ध हैं।",
    about_li1: "हर जरूरत के लिए अनुकूलित सोलर समाधान", about_li2: "उच्च गुणवत्ता उत्पाद और उन्नत तकनीक",
    about_li3: "विशेषज्ञ टीम द्वारा पेशेवर स्थापना", about_li4: "समय पर डिलीवरी और विश्वसनीय सेवा",
    about_btn: "हमारे बारे में और जानें →",
    svc_tag: "हमारी सेवाएं", svc_h2a: "हर जरूरत के लिए", svc_h2b: "संपूर्ण सोलर समाधान",
    svc1_title: "रूफटॉप सोलर समाधान", svc1_desc: "घरों और व्यवसायों के लिए अनुकूलित रूफटॉप सोलर सिस्टम।",
    svc2_title: "व्यावसायिक सोलर समाधान", svc2_desc: "उच्च-प्रदर्शन सोलर सिस्टम से अपने व्यवसाय को ऊर्जा दें।",
    svc3_title: "सोलर स्थापना और कमीशनिंग", svc3_desc: "हमारी विशेषज्ञ टीम द्वारा संपूर्ण स्थापना और कमीशनिंग।",
    svc4_title: "संचालन और रखरखाव", svc4_desc: "हमारी विश्वसनीय O&M सेवाओं से अपने सिस्टम को कुशल बनाए रखें।",
    svc_learn: "और जानें →",
    why_tag: "सोलर क्यों?", why_h2a: "ऐसे फायदे जो", why_h2b: "बदलाव लाते हैं",
    why1_title: "बिजली बिल कम करें", why1_desc: "अपने मासिक बिजली बिल पर 80% तक बचत करें।",
    why2_title: "संपत्ति का मूल्य बढ़ाएं", why2_desc: "सोलर वाले घरों और व्यवसायों का मूल्य अधिक होता है।",
    why3_title: "ऊर्जा स्वतंत्रता", why3_desc: "अपनी खुद की बिजली बनाएं और बढ़ती कीमतों से मुक्त रहें।",
    why4_title: "पर्यावरण के अनुकूल", why4_desc: "कार्बन फुटप्रिंट कम करें और स्वच्छ पृथ्वी में योगदान दें।",
    proc_tag: "हमारी प्रक्रिया", proc_h2: "हमारी सरल 4-चरण प्रक्रिया",
    proc1_title: "परामर्श", proc1_desc: "हम आपकी जरूरतों को समझते हैं और आवश्यकताओं का विश्लेषण करते हैं।",
    proc2_title: "साइट सर्वे", proc2_desc: "हमारे विशेषज्ञ आपकी साइट का दौरा करके विस्तृत मूल्यांकन करते हैं।",
    proc3_title: "प्रस्ताव", proc3_desc: "हम सर्वोत्तम सोलर समाधान के साथ एक कस्टम प्रस्ताव देते हैं।",
    proc4_title: "स्थापना", proc4_desc: "पूर्ण सहायता के साथ पेशेवर स्थापना और कमीशनिंग।",
    testi_tag: "ग्राहक समीक्षा", testi_h2: "हमारे ग्राहक क्या कहते हैं",
    proj_tag: "हमारे प्रोजेक्ट्स", proj_h2: "हमारे कुछ हालिया प्रोजेक्ट्स", proj_view: "सभी प्रोजेक्ट्स देखें →",
    cta_h3: "सोलर ऊर्जा की ओर स्विच करने के लिए तैयार हैं?",
    cta_p: "अपनी ऊर्जा जरूरतों के लिए मुफ्त परामर्श और अनुकूलित समाधान प्राप्त करें।",
    cta_btn: "मुफ्त कोटेशन लें →",
    contact_tag: "संपर्क करें", contact_h2: "मुफ्त कोटेशन लें",
    contact_p: "फॉर्म भरें और हमारी टीम जल्द ही आपसे संपर्क करेगी।",
    contact_info_title: "संपर्क जानकारी",
    contact_phone_label: "फोन", contact_email_label: "ईमेल",
    contact_office_label: "कार्यालय", contact_hours_label: "कार्य समय",
    contact_hours_val: "सोम - शनि: सुबह 9 बजे - शाम 6 बजे", contact_follow: "हमें फॉलो करें",
    form_name: "पूरा नाम", form_name_ph: "अपना नाम दर्ज करें",
    form_phone: "फोन नंबर", form_phone_ph: "अपना फोन नंबर दर्ज करें",
    form_email: "ईमेल पता", form_email_ph: "अपना ईमेल पता दर्ज करें",
    form_city: "शहर", form_city_ph: "अपना शहर दर्ज करें",
    form_service: "आप क्या ढूंढ रहे हैं?", form_service_ph: "एक विकल्प चुनें",
    form_svc1: "रूफटॉप सोलर समाधान", form_svc2: "व्यावसायिक सोलर समाधान",
    form_svc3: "सोलर स्थापना और कमीशनिंग", form_svc4: "संचालन और रखरखाव",
    form_message: "आपका संदेश", form_message_ph: "अपना संदेश लिखें...",
    form_submit: "अभी सबमिट करें →", form_sending: "भेजा जा रहा है...",
    form_success: "✅ संदेश भेजा गया! हम जल्द संपर्क करेंगे।",
    form_error: "❌ कुछ गलत हुआ। कृपया हमें सीधे कॉल करें।",
    footer_desc: "स्मार्ट सोलर समाधानों के साथ एक टिकाऊ भविष्य को ऊर्जा देना।",
    footer_links: "त्वरित लिंक", footer_services: "हमारी सेवाएं", footer_contact: "संपर्क करें",
    footer_copy: "© 2024 नरहरे सोलर सॉल्यूशंस। सर्वाधिकार सुरक्षित।",
    footer_privacy: "गोपनीयता नीति", footer_terms: "नियम और शर्तें",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = (key) => translations[lang][key] || translations["en"][key] || key;
  const toggle = () => setLang((l) => (l === "en" ? "hi" : "en"));
  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
